quizEase/core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.welcome),
    path('welcome/', views.welcome, name='welcome'),
    path('signup/', views.signup, name='signup'),
    path('login_user/', views.login_user, name='login_user'),
    path('error/<str:error_id>/', views.error, name='error'),
]

quizEase/profesor/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.p_home),
    path('p_home/', views.p_home, name='p_home'),
    path('createQuiz/', views.createQuiz, name='createQuiz'),
    path('addQuestion/<int:questionNumber>/', views.addQuestion, name='addQuestion'),
    path('viewQuizzes/', views.viewQuizzes, name='viewQuizzes'),
    path('p_logout/', views.p_logout, name='p_logout'),

    path('delete_quiz/<int:quiz_id>/', views.deleteQuiz, name='deleteQuiz'),
    path('solvedQuizzes/<str:quiz_id>/', views.solvedQuizzes, name='solvedQuizzes'),
]

quizEase/quizEase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('quizEase/', include('core.urls')),
    path('profesor/', include('profesor.urls')),
    path('student/', include('student.urls')),
]

quizEase/core/models.py
from django.db import models

# Create your models here.

from django.db import  models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    isProfesor = models.BooleanField(default=False) # marcheaza un cont cu permisiuni de profesor
    activeQuiz = models.CharField() # id-ul quiz-ului care este editat sau rezolvat la un moment dat
    activeQuestion = models.CharField() # id-ul intrebarii care este editata sau rezolvata la un moment dat
    finishedQuizzes = models.CharField(blank=True) # o lista de quiz-uri care au fost trimise de un student


class Quiz(models.Model):
    id = models.AutoField(primary_key=True) # id unic al quiz-ului
    title = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    instructions = models.CharField(max_length=500)
    showGrade = models.CharField(max_length=100, default="show_grade") # optiunea care permite afisarea notei imediat dupa trimiterea quiz-ului
    allowReturn = models.CharField(max_length=100, default="allow_return") # optiunea care permite intoarcerea la o intrebare precedenta in timpul rezolvarii quiz-ului
    nrOfQuestions = models.IntegerField() # numarul total al intrebarilor quiz-ului
    createdBy = models.ForeignKey(User, on_delete=models.CASCADE) # obiectul User profesor care a creat quiz-ul


class Question(models.Model):
    id = models.AutoField(primary_key=True) # id unic al intrebarii
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE) # quiz-ul din care face parte intrebarea
    text = models.CharField(max_length=100) # textul intrebarii
    answers = models.CharField(max_length=1000) # String care contine raspunsurile, separate prin ";"
    correctAnswer = models.CharField(max_length=100) # Indecsi ai raspunsurilor corecte (unul sau mai multe)
    points = models.IntegerField() # punctele corespunzatoare intrebarii
    questionNumber = models.IntegerField() # numarul intrebarii in cadrul quiz-ului

class Submits(models.Model):
    id = models.AutoField(primary_key=True) # id unic al raspunsului la o intrebare
    student = models.CharField(max_length=100) # email studentului care a raspuns la intrebare
    question_id = models.CharField(max_length=100) # id-ul intrebarii la care s-a raspuns
    quiz_id = models.CharField(max_length=100) # id-ul quizului din care face parte intrebarea
    answers = models.CharField(max_length=1000) # String care contine raspunsurile, separate prin ";"
    points = models.IntegerField() # numarul de puncte acordate, in functie de raspuns

quizEase/profesor/models.py
from django.db import models

# Create your models here.

quizEase/profesor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from core.models import Quiz, Question, Submits, User

# pagina principala pentru utilizator profesor
def p_home(request):
    if request.user.is_authenticated and request.user.isProfesor:
        context = {}
        name = request.user.username.split("@")[0].split(".")
        context['nameStr'] = name[1].title() + " " + name[0].title()
        return render(request, 'homeP.html', context)
    else:
        return redirect('error', error_id='permission_err')

# pagina pentru crerea unui quiz, cu date precum titlu, subiect, instructiuni etc.
def createQuiz(request):
    if request.user.is_authenticated and request.user.isProfesor:

        if request.method == "POST":
            # Extragere informatii generale quiz din formular
            quizTitle = request.POST["quiz_title"]
            quizSubject = request.POST["quiz_subject"]
            quizInstructions = request.POST["quiz_instructions"]
            showGrade = request.POST["quiz_show_grade"]
            allowReturn = request.POST.get('quiz_allow_return', "no_return")
            # creare obiect quiz in baza de date
            quiz = Quiz.objects.create(title=quizTitle,
                                       subject=quizSubject,
                                       instructions=quizInstructions,
                                       showGrade=showGrade,
                                       allowReturn=allowReturn,
                                       createdBy=request.user,
                                       nrOfQuestions = 0)
            # crearea unei intrebari fara date care marcheaza inceputul quizului
            question = Question.objects.create(quiz=quiz,
                                               text=quizTitle,
                                               answers="",
                                               correctAnswer="",
                                               points=0,
                                               questionNumber=0)

            if quiz:
                # setarea quiz-ului curent ca activ
                request.user.activeQuiz = quiz.id
                request.user.save()
                return redirect('addQuestion', questionNumber=1)
            else:
                return redirect('error', error_id='quiz_submission_err')
        return render(request, 'createQuiz.html')
    else:
        return redirect('error', error_id='permission_err')

# pagina prin care se adauga intrebari noi la quiz-ul creat
def addQuestion(request, questionNumber):
    if request.user.is_authenticated and request.user.isProfesor:
        if not request.user.activeQuiz or request.user.activeQuiz == "none":
            # Verifica daca utilizatorul are un quiz activ inainte de a adauga o intrebare
            return redirect('error', error_id='no_active_quiz')

        if request.method == "POST":
            # Se preiau informatiile despre intrebarea introdusa din formular
            activeQuiz = Quiz.objects.get(id=request.user.activeQuiz)
            questionText = request.POST["question_text"]
            answers = request.POST["answers"]
            correct_answer = request.POST["correct_answer"]
            points = request.POST["points"]

            # formatarea raspunsurilor corecte
            answer_list = answers.split(";")
            if len(answer_list[-1]) == 0:
                answer_list.pop()
            correct_answer_index = correct_answer.split(";")
            correct_answer = ""
            if len(correct_answer_index[-1]) == 0:
                correct_answer_index.pop()
            for index in correct_answer_index:
                correct_answer += (answer_list[int(index)]+";")


            # crearea obiectului intrebare in baza de date
            question = Question.objects.create(quiz=activeQuiz,
                                       text=questionText,
                                       answers=answers,
                                       correctAnswer=correct_answer,
                                       points=points,
                                       questionNumber=questionNumber)

            if question:
                if request.POST['submit'] == "next":
                    # se adauga o noua intrebare
                    return redirect('addQuestion', questionNumber=questionNumber+1)
                if request.POST['submit'] == "finish":
                    # se completeaza numarul final de intrebari al quizului si se salveaza quizul
                    activeQuiz.nrOfQuestions = questionNumber
                    activeQuiz.save()
                    # user-ul nu mai are quizul activ
                    request.user.activeQuiz = "none"
                    return redirect('viewQuizzes')
            else:
                return redirect('error', error_id='quiz_submission_err')
        context = {}
        context['questionNumber'] = questionNumber
        return render(request, "addQuestion.html", context)
    else:
        return redirect('error', error_id='permission_err')

# vizualizarea tuturor quiz-urilor create
def viewQuizzes(request):
    if request.user.is_authenticated and request.user.isProfesor:
        context = {}
        # accesarea obiectelor quiz din baza de date, dupa utilizatorul care a creat quiz-ul
        context['quizDatabase'] = Quiz.objects.filter(createdBy=request.user)
        return render(request, 'viewQuizzes.html', context)
    else:
        return redirect('error', error_id='permission_err')

# vizualizarea studentilor care au trimis un anumit quiz
def solvedQuizzes(request, quiz_id):
    if request.user.is_authenticated and request.user.isProfesor:
        context = {"studentDatabase": {}}
        students = User.objects.filter(isProfesor=False)
        for student in students:
            if quiz_id in student.finishedQuizzes.split(';'):
                # selectarea tuturor studentilor care au trimis quiz-ul cu id-ul quizului selectat
                name = student.username.split("@")[0].split(".")
                grade = 0
                submissions = Submits.objects.filter(student=student.username, quiz_id=quiz_id)
                for entry in submissions:
                    # calcularea notei studentului
                    grade += entry.points
                context['studentDatabase'][(name[1].title()[:-2] + " " + name[0].title())] = grade
        return render(request, 'solvedQuizzes.html', context)
    else:
        return redirect('error', error_id='permission_err')

# stergerea unui quiz creat
def deleteQuiz(request, quiz_id):
    if request.user.is_authenticated and request.user.isProfesor:
        # selectarea si stergerea din baza de date, a quiz-ului folosind ID-ul sau
        quiz = Quiz.objects.get(id=quiz_id)
        quiz.delete()
        return redirect('viewQuizzes')
    else:
        return redirect('error', error_id='permission_err')

# terminarea sesiunii
def p_logout(request):
    if request.user.is_authenticated and request.user.isProfesor:
        logout(request)
        return redirect('/quizEase')
    else:
        return redirect('error', error_id='permission_err')

quizEase/profesor/templates/addQuestion.html
{% extends "baseP.html" %}
{% block title %}QuizEase - Add question{% endblock %}
{% load static %}
{% block content %}

     <h2 class="auth-title">Add qestion</h2>

     <form method="post" class=" ">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="form-errors">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <input type="text"
                   name="question_text"
                   id="id_question_text"
                   class="form-control-custom"
                   placeholder="Question text"
                   required>
        </div>

        <div class="form-group">
            <input type="text"
                   name="answers"
                   id="id_answers"
                   class="form-control-custom"
                   placeholder="Answers separated by semicolon">
        </div>

        <div class="form-group">
            <input type="text"
                   name="correct_answer"
                   id="id_correct_answer"
                   class="form-control-custom"
                   placeholder="Correct answers indexes separated by semicolon">
        </div>

         <div class="form-group">
            <input type="text"
                   name="points"
                   id="id_points"
                   class="form-control-custom"
                   placeholder="Points value of current question">
        </div>

        <button type="submit" name="submit" value="finish" class="btn-custom">Finish Quiz</button>
        <button type="submit" name="submit" value="next" class="btn-custom">Next Question</button>

    </form>

{% endblock %}

quizEase/profesor/templates/baseP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}QuizEase - Profesor{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

  <div id="content">
    {% block content %}

    {% endblock %}
  </div>

</body>
</html>

quizEase/profesor/templates/createQuiz.html
{% extends "baseP.html" %}
{% block title %}QuizEase - Create quiz{% endblock %}
{% load static %}
{% block content %}

     <h2 class="auth-title">Create quiz</h2>

     <form method="post" class=" ">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="form-errors">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <input type="text"
                   name="quiz_title"
                   id="id_quiz_title"
                   class="form-control-custom"
                   placeholder="Quiz title"
                   required>
        </div>

        <div class="form-group">
            <input type="text"
                   name="quiz_subject"
                   id="id_quiz_subject"
                   class="form-control-custom"
                   placeholder="Quiz subject">
        </div>

        <div class="form-group">
            <input type="text"
                   name="quiz_instructions"
                   id="id_quiz_instructions"
                   class="form-control-custom"
                   placeholder="Instructions">
        </div>

        <div class="form-group">
            <input type="radio"
                   name="quiz_show_grade"
                   id="id_show_grade"
                   value="show_grade"
                   checked>
            <label style="display: inline; margin-left: 5px; color: #582C5D">show grade after submit</label>
        </div>

        <div class="form-group">
            <input type="radio"
                   name="quiz_show_grade"
                   id="id_hide_grade"
                   value="hide_grade">
            <label style="display: inline; margin-left: 5px; color: #582C5D">show grade after check</label>
        </div>

         <div class="form-group">
            <input type="checkbox"
                   name="quiz_allow_return"
                   id="id_allow_return"
                   value="allow_return">
            <label style="display: inline; margin-left: 5px; color: #582C5D">allow return to previous questions</label>
        </div>


        <button type="submit" class="btn-custom">Add questions</button>

    </form>

{% endblock %}

quizEase/profesor/templates/homeP.html
{% extends "baseP.html" %}
{% block title %}QuizEase - Home{% endblock %}
{% load static %}

{% block content %}

<div class="home-container">
    
    <h1>Hello, Profesor!</h1>
    
    <div class="button-group">
        <a href="{% url 'createQuiz' %}" class="btn-custom">Create quiz</a>
        <a href="{% url 'viewQuizzes' %}" class="btn-custom">View quizzes</a>
        <a href="{% url 'logout' %}" class="btn-custom">Logout</a>
    </div>

</div>

{% endblock %}

quizEase/profesor/templates/solvedQuizzes.html
{% extends "baseP.html" %}
{% block title %}QuizEase - Students{% endblock %}
{% load static %}
{% block content %}

     <h2 class="auth-title">Students</h2>



    {% for key, value in studentDatabase.items %}
        <p>{{ key }} ({{ value }}p)</p>
    {% endfor %}


    <a class="btn-custom" href="{% url 'p_home' %}">Home</a>

{% endblock %}

quizEase/profesor/templates/viewQuizzes.html
{% extends "baseP.html" %}
{% block title %}QuizEase - View quizzes{% endblock %}
{% load static %}
{% block content %}

     <h2 class="auth-title">Quizzes</h2>
<form method="post">
            {% csrf_token %}
    {% for quiz in quizDatabase %}

            <div class="form-group">
                <input type="submit" name="accessQuiz" value="{{quiz.title}}(code:{{quiz.id}})" class="form-control-custom">
                <input type="text" hidden name="quiz_id" value="{{quiz.id}}">
            </div>

            <div class="form-group">
                <p>{{ quiz.subject }}</p>
            </div>

            <div class="form-group">
                <a class="btn-custom" style="width:100px; font-size: 1rem;" href="{% url 'deleteQuiz' quiz.id %}"><img class="btn_icon" src="{% static 'images/bin.png' %}"></a>
                <a class="btn-custom" style="width:100px; font-size: 1rem;" href="{% url 'solvedQuizzes' quiz.id %}"><img class="btn_icon" src="{% static 'images/studenti.png' %}"></a>
            </div>




        <br><br>
    {% endfor %}
</form>

    <a class="btn-custom" href="{% url 'createQuiz' %}">Create quiz</a>
    <a class="btn-custom" href="{% url 'p_home' %}">Home</a>

{% endblock %}